blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/atc-net/[ATC-REPO-NAME]/discussions/new
    about: Is your issue perhaps more of a discussion or question? Please open topics for discussion or questions using the new GitHub Discussions feature. Remember to choose the right category.
  - name: Security problem or issue
    url: atcnet.org@gmail.com
    about: Please report security vulnerabilities here directly to us by mail.    
